### ISSUE TITLE
Setup CI environment

### ISSUE THREAD

**Issue by al-dexter** [unic/sledge#1]
Setup Travis-CI or Snap-SI for the project.

**Comment by olimination** [comment]
First builds looks good :) - thanks.
Should we maybe separate the "integration tests" build in a separate Maven profile and create also two builds, one for simple compilation and one for Integration testing?

**Comment by peterKoellner** [comment]
I don't think that is possible right now with travis-ci: https://github.com/travis-ci/travis-ci/issues/2877
