### ISSUE TITLE
Add possibility to modify config files

### ISSUE THREAD

**Issue by AndreasRabus4unic** [unic/sledge#11]
Irgendwie müssen wir auch Konfigurations- Dateien anpassen, also Properties, XML oder INI Dateien.

Hier geht es nicht um ersetzen (der Datei) sondern Inhalte ändern. (So CRUD operationen halt...)

Also Einträge hinzufügen (davo, dahinter, darunter,...), löschen  und   ändern  (ersetzen und verändern)

Gerade in AEM bei /etc/design die Komponenten Anpassungen gemacht.
Man kann nur die gesamte .content.xm austauschen,  was eigentlich ein bisschen zu grob ist.

Was schön wäre, wenn man sagen könnte:
Füge in dem Eintrag "bla/bluib/irgendwas" zum vorhandenen Wert noch X dazu.  Besonders schön wenn man an AEMs XML Array Notation denkt...
Oder füge unterhalb von /bla/blub/" einen neuen Knoten mit Wert Y dazu, am Anfang oder Ende oder nach Knoten mit wert Z.

Kann man als Modul machen für XML, Properties und Ini Dateien. Sollte man nicht alles mit einem Syntax erschlagen.

Bei XML bietet sich Xpath als suche an, bei properties gibt es nur einen string und bei ini noch diese Gruppen..

Ich denke so was ist mehr als nützlich...

**Comment by olimination** [comment]
Will close this issue because the handling of such configuration files has changed in the past.

The configuration files should be already be provided properly by the DevOps tool or by the package itself.
